name: menukaran
base: core22
adopt-info: menukaran
summary: Securely Create and Manage dekstop files manually.
description: |
  Securely create and manage desktop files, without giving an arbitary app from the internet too much permission. 
grade: stable
confinement: strict
contact: soumyadeepghosh2004@zohomail.in
source-code: https://github.com/soumyaDghosh/menukaran
issues: https://github.com/soumyaDghosh/menukaran/issues/new
website: https://github.com/soumyaDghosh/menukaran

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  menukaran:
    plugin: flutter
    source: https://github.com/soumyaDghosh/menukaran.git
    source-tag: '0.1'
    source-depth: 1
    override-build: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      
    build-packages:
      - curl

slots:
  menukaran:
    interface: dbus
    bus: session
    name: com.soumyaDghosh.menukaran

plugs:
  dot-local-share-applications:
    interface: personal-files
    read:
      - $HOME/.local/share/applications

apps:
  menukaran:
    command: menukaran
    extensions: [ gnome ] 
